name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: "moonrepo/setup-toolchain@v0"
        with:
          auto-install: true

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.8

      - name: コンパイル
        run: bun check-types

      - name: テスト実行
        run: bun run test
