name: WorkersのCI

on:
  pull_request:
    branches:
      - main
    paths:
      - "bff/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bff

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: "moonrepo/setup-toolchain@v0"
        with:
          auto-install: true

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: コンパイル
        run: bun compile
